# Generated by Django 3.0.4 on 2020-04-07 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IBListCommission',
            fields=[
                ('COMPANY_IDX', models.IntegerField()),
                ('LIVE_YN', models.CharField(max_length=1)),
                ('IB_LOGIN', models.IntegerField(primary_key=True, serialize=False)),
                ('TOT_COMMISSION', models.FloatField()),
            ],
            options={
                'verbose_name': 'IBListCommission',
                'verbose_name_plural': 'IBListCommission',
            },
        ),
        migrations.CreateModel(
            name='IBListStructure',
            fields=[
                ('COMPANY_IDX', models.IntegerField()),
                ('LIVE_YN', models.CharField(max_length=1)),
                ('IB_LOGIN', models.IntegerField(primary_key=True, serialize=False)),
                ('TOT_COMMISSION', models.FloatField()),
            ],
            options={
                'verbose_name': 'IBListCommission',
                'verbose_name_plural': 'IBListCommission',
            },
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('S', 'Processed')], default='P', max_length=1)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bank Wire'), ('2', 'i-Account'), ('3', 'Paypal'), ('8', 'Bitcoin'), ('9', 'Ethereum'), ('10', 'GELD Coin'), ('11', 'WTX')], default='', max_length=2)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('mt4_account', models.CharField(blank=True, default='', max_length=36)),
                ('currency', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'USD')], default='1', max_length=1)),
                ('crypto_receiver_address', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('i_account_no', models.CharField(blank=True, default='', max_length=48, null=True)),
                ('status_remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdraw Request',
                'verbose_name_plural': 'Withdraw Requests',
            },
        ),
        migrations.CreateModel(
            name='FxAccountTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_account', models.CharField(default='', max_length=36)),
                ('to_account', models.CharField(default='', max_length=36)),
                ('new_pending_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('transaction_type', models.CharField(choices=[('R', 'Retail')], default='R', max_length=2)),
                ('requesct_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FxAccount Transaction',
                'verbose_name_plural': 'FxAccount Transactions',
            },
        ),
        migrations.CreateModel(
            name='FxAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('L', 'Live MT4 Account')], default='L', max_length=1)),
                ('mt4_account', models.CharField(default='', max_length=36)),
                ('balance', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('D', 'Declined')], default='P', max_length=1)),
                ('ib_status', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('referral_code', models.CharField(blank=True, default='', max_length=6)),
                ('ib_commission', models.FloatField(blank=True, default=0.0)),
                ('base_currency', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'USD')], default='1', max_length=1)),
                ('leverage', models.CharField(choices=[('5', '1:100'), ('6', '1:50'), ('7', '1:25'), ('8', '1:10')], default='1', max_length=1)),
                ('trading_platform', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'MT4')], default='1', max_length=1)),
                ('account_description', models.TextField(blank=True, default='')),
                ('account_name', models.CharField(blank=True, default='', max_length=32)),
                ('account_trader_code', models.CharField(blank=True, default='', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Account',
                'verbose_name_plural': 'Trading Accounts',
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('S', 'Processed')], default='P', max_length=20)),
                ('approval_no', models.CharField(blank=True, default='', max_length=40)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('order_id', models.CharField(blank=True, default='', max_length=40)),
                ('transaction_no', models.CharField(blank=True, default='', max_length=40)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('mt4_account', models.CharField(blank=True, default='', max_length=36)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bank Wire'), ('2', 'i-Account'), ('3', 'Paypal'), ('4', 'EzPay'), ('5', 'i-Pay'), ('6', 'ZotaPay'), ('7', 'ConceptPay'), ('8', 'Bitcoin'), ('9', 'Ethereum'), ('10', 'GELD Coin'), ('11', 'WTX')], default='', max_length=2)),
                ('currency', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'USD')], default='1', max_length=1)),
                ('crypto_sender_address', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('cellphone_number', models.CharField(blank=True, default='', max_length=30)),
                ('gateway_status', models.CharField(blank=True, default='', max_length=20)),
                ('status_remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Transaction',
                'verbose_name_plural': 'Deposit Transactions',
            },
        ),
    ]
