# Generated by Django 3.0.4 on 2020-04-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradingHistory',
        ),
    ]
