# Generated by Django 3.0.4 on 2020-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'USD'), ('2', 'CNY'), ('3', 'BTC'), ('4', 'ETH'), ('5', 'GLC'), ('6', 'WTX')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='gateway_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='mt4_account',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bank Wire'), ('2', 'i-Account'), ('3', 'Paypal'), ('4', 'EzPay'), ('5', 'i-Pay'), ('6', 'ZotaPay'), ('7', 'ConceptPay'), ('8', 'Bitcoin'), ('9', 'Ethereum'), ('10', 'GELD Coin'), ('11', 'WTX')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('S', 'Processed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='depositsavetransaction',
            name='status_remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
