# Generated by Django 3.0.4 on 2020-04-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'USD')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='account_type',
            field=models.CharField(choices=[('0', 'Live MT4 Account')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='base_currency',
            field=models.CharField(blank=True, choices=[('0', 'USD')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='trading_platform',
            field=models.CharField(blank=True, choices=[('0', 'MT4')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'USD')], default='1', max_length=1),
        ),
    ]
