# Generated by Django 3.0.4 on 2020-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxaccount',
            name='pre_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Processed')], default='P', max_length=1),
        ),
    ]
