# Generated by Django 3.0.4 on 2020-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iblistcommission',
            name='COMPANY_IDX',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iblistcommission',
            name='IB_LOGIN',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
