# Generated by Django 3.0.4 on 2020-04-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTradingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mt4_account', models.CharField(default='', max_length=36, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profit', models.FloatField(blank=True, default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DailyTradingHistory',
                'verbose_name_plural': 'DailyTradingHistory',
            },
        ),
    ]
