# Generated by Django 3.0.4 on 2020-04-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxaccount',
            old_name='account_status',
            new_name='status',
        ),
    ]
