# Generated by Django 3.0.4 on 2020-03-26 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fxaccount', '0002_auto_20200326_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], default='D', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('S', 'Processed')], default='P', max_length=20)),
                ('approval_no', models.CharField(blank=True, default='', max_length=40)),
                ('customer_id', models.CharField(blank=True, default='', max_length=20)),
                ('order_id', models.CharField(blank=True, default='', max_length=40)),
                ('transaction_no', models.CharField(blank=True, default='', max_length=40)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('mt4_account', models.CharField(blank=True, default='', max_length=36)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bank Wire'), ('2', 'i-Account'), ('3', 'Paypal'), ('4', 'EzPay'), ('5', 'i-Pay'), ('6', 'ZotaPay'), ('7', 'ConceptPay'), ('8', 'Bitcoin'), ('9', 'Ethereum'), ('10', 'GELD Coin'), ('11', 'WTX')], default='', max_length=2)),
                ('currency', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'USD'), ('2', 'CNY'), ('3', 'BTC'), ('4', 'ETH'), ('5', 'GLC'), ('6', 'WTX')], default='1', max_length=1)),
                ('crypto_sender_address', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=48)),
                ('cellphone_number', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('gateway_status', models.CharField(blank=True, default='', max_length=20)),
                ('status_remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Transaction',
                'verbose_name_plural': 'Deposit Transactions',
            },
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], default='W', max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('S', 'Processed')], default='P', max_length=1)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bank Wire'), ('2', 'i-Account'), ('3', 'Paypal'), ('8', 'Bitcoin'), ('9', 'Ethereum'), ('10', 'GELD Coin'), ('11', 'WTX')], default='', max_length=2)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('mt4_account', models.CharField(blank=True, default='', max_length=36)),
                ('bank_name', models.CharField(blank=True, default='', max_length=48)),
                ('bank_account', models.CharField(blank=True, default='', max_length=48)),
                ('bank_address', models.CharField(blank=True, default='', max_length=128)),
                ('bank_swift', models.CharField(blank=True, default='', max_length=16)),
                ('bank_iban', models.CharField(blank=True, default='', max_length=48)),
                ('bank_branch_name', models.CharField(blank=True, default='', max_length=48)),
                ('bank_branch_code', models.CharField(blank=True, default='', max_length=48)),
                ('intermediary_bank_name', models.CharField(blank=True, default='', max_length=48)),
                ('intermediary_bank_swift', models.CharField(blank=True, default='', max_length=16)),
                ('currency', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'USD'), ('2', 'CNY'), ('3', 'BTC'), ('4', 'ETH'), ('5', 'GLC'), ('6', 'WTX')], default='1', max_length=1)),
                ('beneficiary_full_name', models.CharField(blank=True, default='', max_length=48)),
                ('beneficiary_address', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('paypal_email', models.EmailField(blank=True, default='', max_length=254)),
                ('crypto_receiver_address', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('i_account_no', models.CharField(blank=True, default='', max_length=48, null=True)),
                ('status_remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdraw Request',
                'verbose_name_plural': 'Withdraw Requests',
            },
        ),
        migrations.DeleteModel(
            name='DepositSaveTransaction',
        ),
    ]
