# Generated by Django 3.0.4 on 2020-04-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0002_auto_20200416_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposittransaction',
            old_name='crypto_sender_address',
            new_name='crypto_address',
        ),
        migrations.RenameField(
            model_name='deposittransaction',
            old_name='payment_method',
            new_name='deposit_crypto',
        ),
        migrations.RenameField(
            model_name='withdrawtransaction',
            old_name='crypto_receiver_address',
            new_name='crypto_address',
        ),
        migrations.RenameField(
            model_name='withdrawtransaction',
            old_name='payment_method',
            new_name='withdraw_crypto',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='approval_no',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='sender_memo',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='status_remark',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='transaction_no',
        ),
        migrations.RemoveField(
            model_name='withdrawtransaction',
            name='i_account_no',
        ),
        migrations.RemoveField(
            model_name='withdrawtransaction',
            name='status_remark',
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='crypto_amount',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='cellphone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='crypto_amount',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
