# Generated by Django 3.0.4 on 2020-04-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0002_dailytradinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTradingHistory',
        ),
    ]
