# Generated by Django 3.0.4 on 2020-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0002_delete_tradinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxaccount',
            name='account_type',
            field=models.CharField(choices=[('L', 'Live MT4 Account'), ('D', 'Live IB Account')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='fxaccounttransaction',
            name='account_type',
            field=models.CharField(choices=[('L', 'Live MT4 Account'), ('D', 'Live IB Account')], default='L', max_length=1),
        ),
    ]
