# Generated by Django 3.0.4 on 2020-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0003_auto_20200407_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxaccounttransaction',
            old_name='requesct_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='mt4_account',
            field=models.CharField(default='', max_length=36, null=True),
        ),
    ]
