# Generated by Django 3.0.4 on 2020-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0003_auto_20200420_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='withdrawtransaction',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='cellphone_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='crypto_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='crypto_amount',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='crypto_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
