# Generated by Django 3.0.4 on 2020-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0003_delete_dailytradinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fxaccounttransaction',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='fxaccounttransaction',
            name='new_pending_at',
        ),
        migrations.RemoveField(
            model_name='fxaccounttransaction',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='fxaccounttransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='fxaccounttransaction',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fxaccounttransaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('0', 'USD')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='deposit_crypto',
            field=models.CharField(blank=True, choices=[('0', 'KJ')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Completed')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Completed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='withdraw_crypto',
            field=models.CharField(blank=True, choices=[('0', 'KJ')], default='', max_length=2),
        ),
    ]
