# Generated by Django 3.0.4 on 2020-04-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0004_auto_20200408_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={'verbose_name': 'Request Deposit', 'verbose_name_plural': 'Request Deposit'},
        ),
        migrations.AlterModelOptions(
            name='withdrawtransaction',
            options={'verbose_name': 'Request Withdraw', 'verbose_name_plural': 'Request Withdraw'},
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bank Wire'), ('2', 'i-Account'), ('3', 'Paypal'), ('8', 'Bitcoin'), ('9', 'Ethereum')], default='', max_length=2),
        ),
    ]
