# Generated by Django 3.0.4 on 2020-04-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0004_auto_20200428_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='exchange_rate',
        ),
    ]
