# Generated by Django 3.0.4 on 2020-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0005_auto_20200409_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='gateway_status',
        ),
        migrations.RemoveField(
            model_name='fxaccount',
            name='account_trader_code',
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='sender_memo',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'JKL')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Processed')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='referral_code',
            field=models.CharField(blank=True, default='2002', max_length=6),
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Processed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fxaccounttransaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Processed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Please Choose'), ('1', 'Bitcoin'), ('2', 'Ethereum'), ('3', 'JKL')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('S', 'Processed')], default='P', max_length=1),
        ),
    ]
