# Generated by Django 3.0.4 on 2020-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0006_auto_20200409_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('0', 'Bitcoin'), ('1', 'Ethereum'), ('2', 'JKL')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='fxaccount',
            name='leverage',
            field=models.CharField(choices=[('0', '1:100'), ('1', '1:50'), ('2', '1:25'), ('3', '1:10')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('0', 'Bitcoin'), ('1', 'Ethereum'), ('2', 'JKL')], default='', max_length=2),
        ),
    ]
