# Generated by Django 3.0.4 on 2020-04-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0007_auto_20200413_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxaccount',
            old_name='user',
            new_name='fxuser',
        ),
    ]
