# Generated by Django 3.0.4 on 2020-04-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxaccount', '0010_auto_20200413_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fxaccount',
            old_name='fxuser',
            new_name='user',
        ),
    ]
