# Generated by Django 3.0.3 on 2020-03-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=240)),
                ('user_type', models.CharField(blank=True, choices=[('', 'Please Choose...'), ('R', 'Retail'), ('C', 'Corporate')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=36)),
                ('city', models.CharField(blank=True, max_length=36)),
                ('resident_country', models.CharField(blank=True, max_length=128)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
