# Generated by Django 3.0.4 on 2020-05-06 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resident_country', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=240)),
                ('user_type', models.CharField(blank=True, choices=[('R', 'Retail'), ('I', 'IB')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=36, null=True)),
                ('city', models.CharField(blank=True, max_length=36, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=24, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('0', 'Employed'), ('1', 'Self-Employed'), ('2', 'Unemployed'), ('3', 'Retired'), ('4', 'Student')], default='1', max_length=1, null=True)),
                ('industry', models.CharField(blank=True, max_length=256, null=True)),
                ('employment_position', models.CharField(blank=True, choices=[('0', 'Senior level Management'), ('1', 'Middle Management'), ('2', 'Entry Level')], default='1', max_length=1, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('0', 'Bachelors Degree or Equivalent'), ('1', 'Masters Degree or equivalent'), ('2', 'Phd / Research Degree'), ('3', 'Diploma or Equivalent')], default='1', max_length=1, null=True)),
                ('annual_income', models.CharField(blank=True, choices=[('0', 'Less Than 10,000'), ('1', '10,000 to 50,000'), ('2', '50,000 to 100,000'), ('3', 'Over 100,000')], default='1', max_length=1, null=True)),
                ('income_source', models.CharField(blank=True, choices=[('0', 'salary'), ('1', 'Business/Profession'), ('2', 'capital gain'), ('3', 'House Property'), ('4', 'other sources')], default='1', max_length=1, null=True)),
                ('expected_deposit', models.CharField(blank=True, choices=[('0', 'Employed'), ('1', 'Self-Employed'), ('2', 'Unemployed'), ('3', 'Retired'), ('4', 'Student')], default='1', max_length=1, null=True)),
                ('trading_experience', models.CharField(blank=True, choices=[('0', 'Y'), ('1', 'N')], default='1', max_length=1, null=True)),
                ('trading_period', models.CharField(blank=True, choices=[('0', 'I have a relevant education/professional qualification'), ('1', 'I regularly monitor the news/markets'), ('2', 'I have read educational material on FX trading'), ('3', 'all of the above'), ('4', 'none of above')], default='1', max_length=1, null=True)),
                ('referral_code', models.CharField(blank=True, default='2002', max_length=36, null=True)),
                ('referral_website', models.URLField(blank=True, default='', max_length=128, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('0', 'Welcome'), ('1', 'PENDING EMAIL ADDRESS'), ('2', 'CONFIRMED EMAIL ADDRESS'), ('3', 'PENDING PROFILE'), ('4', 'CONFIRMED PROFILE'), ('5', 'PENDING DOCUMENTS'), ('6', 'CONFIRMED DOCUMENTS'), ('7', 'PENDING OPEN ACCOUNT'), ('8', 'CONFIRMED OPEN ACCOUNT'), ('9', 'PENDING MAKE DEPOSIT'), ('10', 'CONFIRMED MAKE DEPOSIT')], default='1', max_length=2)),
                ('kj_address', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.FxUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IntroducingBroker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_idx', models.IntegerField(blank=True, default=1, null=True)),
                ('ib_code', models.IntegerField(blank=True, null=True)),
                ('ib_name', models.CharField(blank=True, max_length=36)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('live_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('send_report', models.CharField(blank=True, max_length=1, null=True)),
                ('referralurl', models.URLField(blank=True, null=True)),
                ('ib_website', models.URLField(blank=True, default='', max_length=128, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('fxuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=69, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.IntroducingBroker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FxUserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_photo_id', models.FileField(blank=True, null=True, upload_to=user.models.user_id_directory_path)),
                ('doc_photo_id_status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1)),
                ('doc_photo_id_updated_at', models.DateTimeField(auto_now=True)),
                ('doc_proof_of_residence', models.FileField(blank=True, null=True, upload_to=user.models.user_residence_directory_path)),
                ('doc_proof_of_residence_status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1)),
                ('doc_proof_of_residence_updated_at', models.DateTimeField(auto_now=True)),
                ('doc_photo_id_2', models.FileField(blank=True, null=True, upload_to=user.models.user_id_directory_path)),
                ('doc_photo_id_2_status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1)),
                ('doc_photo_id_2_updated_at', models.DateTimeField(auto_now=True)),
                ('doc_proof_of_residence_2', models.FileField(blank=True, null=True, upload_to=user.models.user_residence_directory_path)),
                ('doc_proof_of_residence_2_status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1)),
                ('doc_proof_of_residence_2_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fxuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplyIntroducingBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_idx', models.IntegerField(blank=True, default=1, null=True)),
                ('parent_idx', models.IntegerField(blank=True, default=69, null=True)),
                ('ib_code', models.IntegerField(blank=True, null=True)),
                ('ib_name', models.CharField(blank=True, max_length=36)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('live_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('send_report', models.CharField(blank=True, max_length=1, null=True)),
                ('back_index', models.IntegerField(blank=True, null=True)),
                ('referralurl', models.URLField(blank=True, null=True)),
                ('ib_website', models.URLField(blank=True, default='', max_length=128, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1, null=True)),
                ('fxuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
