# Generated by Django 3.0.4 on 2020-04-22 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyIntroducingBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ib_name', models.CharField(blank=True, max_length=36)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('live_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('send_report', models.CharField(blank=True, max_length=1, null=True)),
                ('ib_website', models.URLField(blank=True, default='', max_length=128, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1, null=True)),
                ('fxuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
