# Generated by Django 3.0.4 on 2020-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducingbroker',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='introducingbroker',
            name='parent_idx',
            field=models.IntegerField(blank=True, default=69, null=True),
        ),
    ]
