# Generated by Django 3.0.4 on 2020-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxuser',
            name='Nationality',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='annual_income',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Less Than 10,000'), ('2', '10,000 to 50,000'), ('3', '50,000 to 100,000'), ('4', 'Over 100,000')], default='1', max_length=1, null=True, verbose_name='annual income'),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='city',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Bachelors Degree or Equivalent'), ('2', 'Masters Degree or equivalent'), ('3', 'Phd / Research Degree'), ('4', 'Diploma or Equivalent')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='employment_position',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Senior level Management'), ('2', 'Middle Management'), ('3', 'Entry Level')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Employed'), ('2', 'Self-Employed'), ('3', 'Unemployed'), ('4', 'Retired'), ('5', 'Student')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='expected_deposit',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Employed'), ('2', 'Self-Employed'), ('3', 'Unemployed'), ('4', 'Retired'), ('5', 'Student')], default='1', max_length=1, null=True, verbose_name='expected deposit'),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='income_source',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Employed'), ('2', 'Self-Employed'), ('3', 'Unemployed'), ('4', 'Retired'), ('5', 'Student')], default='1', max_length=1, null=True, verbose_name='income source'),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='industry',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='trading_experience',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Y'), ('2', 'N')], default='1', max_length=1, null=True, verbose_name='trading experience'),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='trading_period',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'I have a relevant education/professional qualification'), ('2', 'I regularly monitor the news/markets'), ('3', 'I have read educational material on FX trading'), ('4', 'all of the above'), ('5', 'none of above')], default='1', max_length=1, null=True, verbose_name='trading period'),
        ),
    ]
