# Generated by Django 3.0.4 on 2020-03-23 10:03

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fxuser',
            managers=[
                ('objects', user.models.FxUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fxuser',
            name='Nationality',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='resident_country',
            field=models.CharField(max_length=240),
        ),
    ]
