# Generated by Django 3.0.4 on 2020-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200401_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducingbroker',
            name='back_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
