# Generated by Django 3.0.4 on 2020-05-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200506_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUserCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('content', models.CharField(default='', max_length=4000)),
            ],
            options={
                'db_table': 'request_call_user',
            },
        ),
    ]
