# Generated by Django 3.0.4 on 2020-04-09 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200408_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxuser',
            name='user_status',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'PENDING EMAIL ADDRESS'), ('2', 'CONFIRMED EMAIL ADDRESS'), ('3', 'PENDING PROFILE'), ('4', 'CONFIRMED PROFILE'), ('5', 'PENDING DOCUMENTS'), ('6', 'CONFIRMED DOCUMENTS'), ('7', 'PENDING OPEN ACCOUNT'), ('8', 'CONFIRMED OPEN ACCOUNT'), ('9', 'PENDING MAKE DEPOSIT'), ('10', 'CONFIRMED MAKE DEPOSIT')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='fxuserdocument',
            name='fxuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
