# Generated by Django 3.0.4 on 2020-04-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200416_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introducingbroker',
            name='password',
        ),
    ]
