# Generated by Django 3.0.4 on 2020-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_introducingbroker_back_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducingbroker',
            name='referralurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='referral_website',
            field=models.URLField(blank=True, default='', max_length=128, null=True),
        ),
    ]
