# Generated by Django 3.0.4 on 2020-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200422_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxuser',
            name='kj_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
