# Generated by Django 3.0.4 on 2020-04-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_introducingbroker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducingbroker',
            name='ib_website',
            field=models.URLField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='introducingbroker',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
