# Generated by Django 3.0.4 on 2020-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200409_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxuser',
            name='annual_income',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Less Than 10,000'), ('2', '10,000 to 50,000'), ('3', '50,000 to 100,000'), ('4', 'Over 100,000')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='expected_deposit',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Employed'), ('2', 'Self-Employed'), ('3', 'Unemployed'), ('4', 'Retired'), ('5', 'Student')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='income_source',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Employed'), ('2', 'Self-Employed'), ('3', 'Unemployed'), ('4', 'Retired'), ('5', 'Student')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='trading_experience',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'Y'), ('2', 'N')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fxuser',
            name='trading_period',
            field=models.CharField(blank=True, choices=[('', 'Please Choose...'), ('1', 'I have a relevant education/professional qualification'), ('2', 'I regularly monitor the news/markets'), ('3', 'I have read educational material on FX trading'), ('4', 'all of the above'), ('5', 'none of above')], default='1', max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='UserInvoices',
        ),
    ]
