# Generated by Django 3.0.4 on 2020-05-06 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100)),
                ('confirmations', models.IntegerField(default=0)),
                ('from_address', models.CharField(max_length=50)),
                ('to_address', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='', max_length=42)),
                ('kj_balance', models.FloatField(blank=True, default=0.0)),
                ('eth_balance', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallet',
            },
        ),
    ]
