# Generated by Django 3.0.4 on 2020-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200423_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='eth_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='kj_balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
