# Generated by Django 3.0.4 on 2020-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20200423_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100)),
                ('confirmations', models.IntegerField(default=0)),
                ('from_address', models.CharField(max_length=50)),
                ('to_address', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
    ]
